name: PR - Main

on:
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  check-dependencies:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3.1.1
      - name: Assert dependency versions
        run: node common/scripts/install-run-rush.js check
  assert-changes:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: read
    outputs:
      ct: ${{ steps.filter.output.ct }}
      core: ${{ steps.filter.outputs.core }}
      eventstoredb: ${{ steps.filter.outputs.eventstoredb }}
      packages: ${{ steps.filter.output.changes }}
    steps:
    - uses: dorny/paths-filter@v2
      id: filter
      with:
        filters: |
          ct: packages/ct/**
          core: packages/core/**
          eventstoredb: packages/eventstoredb/**
          messenger: packages/messenger/**
  test-utils:
    needs: assert-changes
    runs-on: ubuntu-latest
    if: ${{ needs.assert-changes.outputs.ct == true || needs.assert-changes.outputs.messenger == true }}
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3.1.1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Rush Install
        run: node common/scripts/install-run-rush.js install
      - name: Build and Test packages/class-transformer-storage
        if: ${{ needs.assert-changes.outputs.ct == true }}
        run: | 
          node common/scripts/install-run-rush.js build -T class-transformer-storage && \
          npm run test --prefix packages/class-transformer-storage
      - name: Build and Test packages/messenger
        if: ${{ needs.assert-changes.outputs.messenger == true }}
        run: | 
          node common/scripts/install-run-rush.js build -T nest-messenger && \
          npm run test --prefix packages/messenger
  test-core:
    needs: assert-changes
    runs-on: ubuntu-latest
    if: ${{ needs.assert-changes.outputs.core == true }}
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3.1.1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Rush Install
        run: node common/scripts/install-run-rush.js install
      - name: Build
        run: | 
          node common/scripts/install-run-rush.js build -T @nest-cqrs/core
      - name: Test
        run: | 
          npm run test --prefix packages/messenger
  test-core-dependents:
    needs: assert-changes
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
        package: ${{ fromJSON(needs.changes.outputs.packages) }}
        exclude:
        - package: ct
        - package: core
        - package: messenger
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3.1.1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Rush Install
        run: node common/scripts/install-run-rush.js install
      - name: Build
        run: | 
          node common/scripts/install-run-rush.js build -T @nest-cqrs/${{ matrix.package }}
      - name: Test
        run: | 
          npm run test --prefix packages/${{ matrix.package }}
